import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const links = [
  { href: "/products", name: "Products" },
  { href: "/register", name: "Registeer" },
  { href: "/navigatingprogrammatically", name: "Prog-nav" },
  { href: "/profile", name: "Profile" },
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <div className="flex justify-center text-3xl">
        
        
        {links.map((link) => {
          return (
            <Link href={link.href} key={link.name} className=" ml-4 ">
              {link.name}
            </Link>
          );
        })}
        
        </div>
        <div className="relative left-20 top-10">
        {children}
        </div>
      </body>
    </html>
  );
}
